runtime: nodejs12
env_variables:
  INSTANCE_UNIX_SOCKET: /cloudsql/asu-marketplace-app:us-west2:product-listings-instance
  DB_USER: root
  DB_PASS: 
  DB_NAME: product-database
handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
  # Catch all handler to index.html
  - url: /.*
    static_files: build/index.html
    upload: build/index.html